

install.packages("data.table")
install.packages("snow")
install.packages("fasttime")
install.packages("fst")
install.packages("lubridate")
install.packages("zoo")
install.packages("plotROC")
install.packages("RcppRoll")
install.packages("glmnet")
install.packages("Ckmeans.1d.dp")
install.packages("gtools")
install.packages("igraph")
install.packages("here")
install.packages("dygraphs")
install.packages(c("xgboost", "dygraphs", "precrec"))
install.packages("reticulate")
install.packages("pROC")
install.packages("freqdom")
install.packages("caret")
install.packages("e1071")
